/* B-NAN core registry — the honest map of what actually runs.
   Verified directly against EmulatorJS's own source (data/src/consts.js,
   version 4.3.0-pre) rather than assumed. If EmulatorJS adds a system,
   flip its `available` flag here and it shows up everywhere in the app.

   RB_SYSTEMS   -- one entry per playable-or-not *system*, used for the
                   sidebar, importer, and player. `thumbRepo` is the
                   system's folder name on thumbnails.libretro.com (the
                   same CDN RetroArch itself uses for box art) -- see
                   artwork.js. It's a best-effort match against libretro's
                   public naming convention; systems without one just
                   skip auto-art and fall back to the placeholder tile,
                   same as a lookup miss would.
   RB_CORE_LIST -- the full named-core wishlist (every emulator you'd
                   find across RetroArch/standalone builds), each mapped
                   to a system with an honest note about what actually
                   powers it in B-NAN today. */

const RB_SYSTEMS = [
  // ---- available today, via EmulatorJS/libretro cores (verified) ----
  { id: "nes", name: "NES / Famicom", group: "Nintendo", extensions: ["nes", "fds", "unf", "unif"], emulatorjsCore: "nes", engine: "FCEUmm", altEngines: ["Nestopia"], thumbRepo: "Nintendo - Nintendo Entertainment System", available: true },
  { id: "snes", name: "SNES / Super Famicom", group: "Nintendo", extensions: ["sfc", "smc", "fig", "swc"], emulatorjsCore: "snes", engine: "Snes9x", thumbRepo: "Nintendo - Super Nintendo Entertainment System", available: true, note: "bsnes is available as an alternate engine on the 'nightly' core channel; the stable channel plays SNES via Snes9x only." },
  { id: "gb", name: "Game Boy / Color", group: "Nintendo", extensions: ["gb", "gbc"], emulatorjsCore: "gb", engine: "Gambatte", thumbRepo: "Nintendo - Game Boy", available: true },
  { id: "gba", name: "Game Boy Advance", group: "Nintendo", extensions: ["gba"], emulatorjsCore: "gba", engine: "mGBA", thumbRepo: "Nintendo - Game Boy Advance", available: true },
  { id: "nds", name: "Nintendo DS", group: "Nintendo", extensions: ["nds", "dsi"], emulatorjsCore: "nds", engine: "melonDS", altEngines: ["DeSmuME", "DeSmuME 2015"], thumbRepo: "Nintendo - Nintendo DS", available: true },
  { id: "n64", name: "Nintendo 64", group: "Nintendo", extensions: ["n64", "z64", "v64", "ndd"], emulatorjsCore: "n64", engine: "Mupen64Plus-Next", altEngines: ["ParaLLEl N64"], thumbRepo: "Nintendo - Nintendo 64", available: true, warning: "Demanding — expect slowdown on older machines." },
  { id: "3ds", name: "Nintendo 3DS", group: "Nintendo", extensions: ["3ds", "cci", "cxi"], emulatorjsCore: "azahar", engine: "Azahar (a Citra continuation)", thumbRepo: "Nintendo - Nintendo 3DS", available: true, requiresChannel: "nightly-frozen", requiresThreads: true, warning: "Very demanding — this is genuinely heavy emulation (a full 3DS) even with that. Permanently vendored locally (see docs/BUILD.md), not fetched live, so this works offline like every other system despite not being in EmulatorJS's own numbered stable release yet.", note: "emulatorjsCore is 'azahar', not '3ds' -- verified directly against EmulatorJS's own source (data/src/consts.js): the system id and the actual core/file-naming id aren't always the same string, and this one differs. Getting this wrong means the core simply never loads." },
  { id: "psx", name: "PlayStation", group: "Sony", extensions: ["cue", "bin", "img", "chd", "pbp", "m3u"], emulatorjsCore: "psx", engine: "PCSX-ReARMed", altEngines: ["Beetle PSX HW"], thumbRepo: "Sony - PlayStation", available: true },
  { id: "psp", name: "PSP", group: "Sony", extensions: ["iso", "cso", "pbp"], emulatorjsCore: "psp", engine: "PPSSPP", thumbRepo: "Sony - PlayStation Portable", available: true, requiresThreads: true, warning: "Demanding — needs a fairly modern machine/browser." },
  { id: "segaMS", name: "Sega Master System / SG-1000", group: "Sega", extensions: ["sms", "sg"], emulatorjsCore: "segaMS", engine: "SMS Plus", altEngines: ["Genesis Plus GX", "PicoDrive"], thumbRepo: "Sega - Master System - Mark III", available: true, note: "Also covers the earlier SG-1000 (.sg) — Genesis Plus GX, one of this system's alternate cores, natively supports it (verified against the core's own docs at docs.libretro.com/library/genesis_plus_gx, which lists SG-1000 as a first-class supported system with .sg as a real extension) -- same 'one core, several related systems' pattern already used for PC Engine/SuperGrafx/PCE-CD below." },
  { id: "segaMD", name: "Genesis / Mega Drive", group: "Sega", extensions: ["md", "gen", "smd", "bin"], emulatorjsCore: "segaMD", engine: "Genesis Plus GX", altEngines: ["PicoDrive"], thumbRepo: "Sega - Mega Drive - Genesis", available: true },
  { id: "segaGG", name: "Game Gear", group: "Sega", extensions: ["gg"], emulatorjsCore: "segaGG", engine: "Genesis Plus GX", thumbRepo: "Sega - Game Gear", available: true },
  { id: "segaCD", name: "Sega CD", group: "Sega", extensions: ["cue", "bin", "chd", "iso"], emulatorjsCore: "segaCD", engine: "Genesis Plus GX", altEngines: ["PicoDrive"], thumbRepo: "Sega - Mega-CD - Sega CD", available: true },
  { id: "sega32x", name: "Sega 32X", group: "Sega", extensions: ["32x"], emulatorjsCore: "sega32x", engine: "PicoDrive", thumbRepo: "Sega - 32X", available: true },
  { id: "segaSaturn", name: "Sega Saturn", group: "Sega", extensions: ["cue", "bin", "chd", "iso"], emulatorjsCore: "segaSaturn", engine: "Yabause", thumbRepo: "Sega - Saturn", available: true, warning: "Demanding — some games will be slow." },
  { id: "atari2600", name: "Atari 2600", group: "Atari", extensions: ["a26", "bin"], emulatorjsCore: "atari2600", engine: "Stella 2014", thumbRepo: "Atari - 2600", available: true },
  { id: "atari5200", name: "Atari 5200", group: "Atari", extensions: ["a52", "bin"], emulatorjsCore: "atari5200", engine: "a5200", thumbRepo: "Atari - 5200", available: true },
  { id: "atari7800", name: "Atari 7800", group: "Atari", extensions: ["a78", "bin"], emulatorjsCore: "atari7800", engine: "ProSystem", thumbRepo: "Atari - 7800", available: true },
  { id: "lynx", name: "Atari Lynx", group: "Atari", extensions: ["lnx"], emulatorjsCore: "lynx", engine: "Handy", thumbRepo: "Atari - Lynx", available: true },
  { id: "jaguar", name: "Atari Jaguar", group: "Atari", extensions: ["j64", "jag"], emulatorjsCore: "jaguar", engine: "Virtual Jaguar", thumbRepo: "Atari - Jaguar", available: true },
  { id: "vb", name: "Virtual Boy", group: "Nintendo", extensions: ["vb"], emulatorjsCore: "vb", engine: "Beetle VB", thumbRepo: "Nintendo - Virtual Boy", available: true },
  { id: "ws", name: "WonderSwan / Color", group: "Bandai", extensions: ["ws", "wsc"], emulatorjsCore: "ws", engine: "Beetle WonderSwan", thumbRepo: "Bandai - WonderSwan", available: true },
  { id: "ngp", name: "Neo Geo Pocket / Color", group: "SNK", extensions: ["ngp", "ngc"], emulatorjsCore: "ngp", engine: "Beetle NGP", thumbRepo: "SNK - Neo Geo Pocket", available: true },
  { id: "coleco", name: "ColecoVision", group: "Coleco", extensions: ["col", "rom"], emulatorjsCore: "coleco", engine: "GearColeco", thumbRepo: "Coleco - ColecoVision", available: true },
  { id: "pce", name: "PC Engine / TurboGrafx-16", group: "NEC", extensions: ["pce", "cue", "bin"], emulatorjsCore: "pce", engine: "Beetle PCE", thumbRepo: "NEC - PC Engine - TurboGrafx 16", available: true, note: "Also covers PC Engine CD and SuperGrafx titles." },
  { id: "pcfx", name: "PC-FX", group: "NEC", extensions: ["cue", "bin", "iso"], emulatorjsCore: "pcfx", engine: "Beetle PC-FX", thumbRepo: "NEC - PC-FX", available: true },
  { id: "arcade", name: "Arcade (FinalBurn Neo)", group: "Arcade", extensions: ["zip"], emulatorjsCore: "arcade", engine: "FinalBurn Neo", altEngines: ["FBA CPS-1", "FBA CPS-2"], thumbRepo: "FBNeo - Arcade Games", available: true, note: "Covers most Neo Geo, CPS-1/2, and general arcade sets." },
  { id: "mame", name: "Arcade (MAME)", group: "Arcade", extensions: ["zip"], emulatorjsCore: "mame", engine: "MAME 2003-Plus", altEngines: ["MAME 2003"], thumbRepo: "MAME", available: true },
  { id: "3do", name: "Panasonic 3DO", group: "Panasonic", extensions: ["cue", "bin", "iso", "chd"], emulatorjsCore: "3do", engine: "Opera", thumbRepo: "The 3DO Company - 3DO", available: true },
  { id: "amiga", name: "Commodore Amiga", group: "Commodore", extensions: ["adf", "ipf", "dms", "lha"], emulatorjsCore: "amiga", engine: "PUAE", thumbRepo: "Commodore - Amiga", available: true },
  { id: "amigacd32", name: "Commodore Amiga CD32", group: "Commodore", extensions: ["iso", "cue", "chd"], emulatorjsCore: "amiga", engine: "PUAE", available: true, note: "Not a separate core -- the CD32 was Commodore's own Amiga-based console, and it runs on the exact same PUAE core as regular Amiga above. Set the model to CD32 in the in-game core options menu (the gear icon) and provide the CD32 Kickstart ROM the same way you would the regular Amiga Kickstart -- B-NAN doesn't auto-detect this from the disc image." },
  { id: "c64", name: "Commodore 64", group: "Commodore", extensions: ["d64", "t64", "prg", "crt"], emulatorjsCore: "c64", engine: "VICE (x64sc)", thumbRepo: "Commodore - 64", available: true },
  { id: "c128", name: "Commodore 128", group: "Commodore", extensions: ["d64", "prg"], emulatorjsCore: "c128", engine: "VICE (x128)", thumbRepo: "Commodore - 128", available: true },
  { id: "pet", name: "Commodore PET", group: "Commodore", extensions: ["d64", "prg"], emulatorjsCore: "pet", engine: "VICE (xpet)", thumbRepo: "Commodore - PET", available: true },
  { id: "plus4", name: "Commodore Plus/4", group: "Commodore", extensions: ["d64", "prg"], emulatorjsCore: "plus4", engine: "VICE (xplus4)", thumbRepo: "Commodore - Plus-4", available: true },
  { id: "vic20", name: "Commodore VIC-20", group: "Commodore", extensions: ["d64", "prg"], emulatorjsCore: "vic20", engine: "VICE (xvic)", thumbRepo: "Commodore - VIC-20", available: true },
  { id: "dos", name: "DOS PCs", group: "PC", extensions: ["zip", "iso", "exe"], emulatorjsCore: "dos", engine: "DOSBox Pure", thumbRepo: "DOS", available: true, requiresThreads: true },
  { id: "intv", name: "Intellivision", group: "Mattel", extensions: ["int", "bin", "rom"], emulatorjsCore: "freeintv", engine: "FreeIntv", thumbRepo: "Mattel - Intellivision", available: true, requiresChannel: "nightly-frozen", note: "emulatorjsCore is 'freeintv', not 'intv' -- same class of bug as the 3DS entry, same fix: verified against EmulatorJS's own consts.js rather than assumed. Permanently vendored locally (see docs/BUILD.md) despite not being in the numbered stable release yet." },

  // ---- on the list, not playable yet in this build ----
  { id: "switch", name: "Nintendo Switch", group: "Nintendo", extensions: ["nsp", "xci"], emulatorjsCore: null, available: false, note: "There is no browser/WASM-ready Switch core anywhere, in this app or otherwise. The two real standalone Switch emulators, Yuzu and Ryujinx, were both shut down in 2024 following Nintendo's legal action against their maintainers. A newer project, NxEmu, exists but is native desktop software (not browser-embeddable) and, by its own progress reports, only a handful of games run at all. B-NAN isn't going to bundle or wire up an early-stage native emulator with this much legal and technical uncertainty — this row exists so that's said plainly instead of silently ignored." },
  { id: "gamecube_wii", name: "GameCube / Wii", group: "Nintendo", extensions: ["iso", "rvz", "wbfs"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "dolphin" }, note: "No browser-ready core exists (there isn't one anywhere, not just in B-NAN). Playable in the .dmg/.exe/.AppImage desktop builds ONLY, and only if Dolphin was actually fetched and bundled at build time (Dolphin's official builds have to be downloaded by a human, not fetched automatically — see docs/NATIVE_EMULATORS.md). If it wasn't, this row still shows as unavailable, same as here." },
  { id: "dreamcast", name: "Sega Dreamcast", group: "Sega", extensions: ["cdi", "gdi", "chd"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "flycast" }, note: "No browser-ready core exists. Playable in the desktop builds ONLY, via a bundled native Flycast — see docs/NATIVE_EMULATORS.md." },
  { id: "playstation2", name: "PlayStation 2", group: "Sony", extensions: ["iso", "chd"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "pcsx2" }, note: "No browser-ready PS2 core exists (Play! is a desktop-only project). Playable in the desktop builds ONLY, via a bundled native PCSX2 — see docs/NATIVE_EMULATORS.md." },
  { id: "msx", name: "MSX / MSX2", group: "Microsoft/ASCII", extensions: ["rom", "dsk"], emulatorjsCore: null, available: false, note: "A real, actively-maintained, embeddable browser emulator exists for this (WebMSX) -- but it has no license at all (no LICENSE file, nothing in package.json, nothing in the README). Publicly viewable on GitHub isn't the same as free to redistribute; without an explicit license, bundling it into B-NAN isn't something that can be done legally. This is a licensing blocker, not a technical one -- if that ever changes, this becomes straightforward to add." },
  { id: "amstradcpc", name: "Amstrad CPC", group: "Amstrad", extensions: ["dsk", "cdt"], emulatorjsCore: null, available: false, note: "Checked directly (not assumed): no actively-maintained, production-ready browser emulator exists for this yet. The candidates found were either a solo hobby project with no documented embedding path, or a narrow single-game showcase, not a general emulator." },
  { id: "zxspectrum", name: "ZX Spectrum", group: "Sinclair", extensions: ["sna", "z80", "szx", "tap", "tzx"], emulatorjsCore: "jsspeccy3", engine: "JSSpeccy 3", available: true, altEngine: { type: "jsspeccy3", embedPath: "vendor-jsspeccy3/embed.html" }, note: "Not an EmulatorJS/libretro core -- powered by JSSpeccy 3 (GPL-3.0, github.com/gasman/jsspeccy3), vendored locally and verified working end-to-end. Save states aren't available for this system in B-NAN yet; JSSpeccy doesn't expose that as a simple external API the way EmulatorJS does." },
  { id: "bbcmicro", name: "BBC Micro", group: "Acorn", extensions: ["ssd", "dsd"], emulatorjsCore: "jsbeeb", engine: "jsbeeb", available: true, altEngine: { type: "jsbeeb", embedPath: "vendor-jsbeeb/index.html" }, note: "Not an EmulatorJS/libretro core -- powered by jsbeeb (GPL-3.0, github.com/mattgodbolt/jsbeeb), built from source and vendored locally, verified working end-to-end. It has its own built-in save-state menu (inside the emulator itself) but B-NAN's own Save/Load buttons don't drive it yet." },
  { id: "atari8bit", name: "Atari 8-bit / XEGS", group: "Atari", extensions: ["atr", "xex", "car", "rom", "bin"], emulatorjsCore: "sfotty-pie", engine: "Sfotty Pie", available: true, altEngine: { type: "atari8bit", embedPath: "a8/emu" }, note: "Not an EmulatorJS/libretro core -- powered by Sfotty Pie (MIT, github.com/cyco130/sfotty-pie), built from source and vendored locally at web/a8/, verified working end-to-end. Covers the Atari 400/800/XL/XE line and the XEGS. Its router uses hardcoded absolute paths like /a8/emu (not configurable via a prefix), so it's vendored at exactly that path rather than under a generic vendor-* folder like the other alt engines -- unmodified source, just a build-time base-path flag and a matching URL rewrite rule on B-NAN's own static server." },

  // ---- available via RetroArch's own official web player (web.libretro.com),
  // vendored at web/vendor-retroarch-web/ -- these are real libretro cores,
  // but EmulatorJS itself doesn't build/host any of them (checked directly
  // against its actual core list, not assumed), so they go through
  // RetroArch's own heavier Emscripten build instead. Mechanism verified
  // working end-to-end by hand (WASM loads, virtual filesystem mounts,
  // RetroArch boots straight into content via direct-launch argv, WebGL
  // actively renders) before any of these were added -- see embed.html's
  // header comment for the full story. Each core's own repo/license was
  // checked directly, not assumed.
  { id: "uzebox", name: "Uzebox", group: "Homebrew", extensions: ["uze"], emulatorjsCore: null, engine: "Uzem", available: true, altEngine: { type: "retroarch-web", embedPath: "vendor-retroarch-web/embed.html", core: "uzem" }, thumbRepo: "Uzebox", note: "Uzem (GPLv3, part of the official libretro core collection), via RetroArch's web player -- not EmulatorJS, which doesn't build this core." },
  { id: "microw8", name: "MicroW8", group: "Fantasy console", extensions: ["uw8"], emulatorjsCore: null, engine: "uw8-libretro", available: true, altEngine: { type: "retroarch-web", embedPath: "vendor-retroarch-web/embed.html", core: "uw8" }, note: "exoticorn/microw8 + uw8-libretro (both Unlicense), via RetroArch's web player. Stronger footing than the TIC-80/WASM-4 entries below, which only have their own separate web players, not a libretro core B-NAN can vendor the same way as everything else." },
  { id: "lowresnx", name: "LowRes NX", group: "Fantasy console", extensions: ["nx"], emulatorjsCore: null, engine: "lowresnx (libretro)", available: true, altEngine: { type: "retroarch-web", embedPath: "vendor-retroarch-web/embed.html", core: "lowresnx" }, note: "timoinutilis/lowres-nx (zlib license -- confirmed by reading the actual LICENSE file, not a secondary source that wrongly claims LGPLv3), via RetroArch's web player." },
  { id: "pc88", name: "NEC PC-8000 / PC-8800", group: "NEC", extensions: ["d88", "t88"], emulatorjsCore: null, engine: "QUASI88", available: true, altEngine: { type: "retroarch-web", embedPath: "vendor-retroarch-web/embed.html", core: "quasi88" }, note: "QUASI88 (BSD-3-Clause), via RetroArch's web player." },
  { id: "pc98", name: "NEC PC-9800", group: "NEC", extensions: ["d98", "fdi", "hdi"], emulatorjsCore: null, engine: "Neko Project II Kai", available: false, note: "NP2kai / Neko Project II Kai is real and licensed (MIT -- confirmed by reading the actual LICENSE file) and its WASM build genuinely loads via RetroArch's web player, same mechanism as B-NAN's other RetroArch-web systems -- but it throws a real, reproducible runtime error ('null function' / reading getContext of undefined) this core alone doesn't hit, even after fixing an initial wasm-path 404. Left OFF rather than shipped half-working; the vendored core files and altEngine wiring are already in place at web/vendor-retroarch-web/ for whoever debugs this next -- see embed.html." },
  { id: "thomson", name: "Thomson MO/TO", group: "Thomson", extensions: ["fd", "k7", "m5", "m7"], emulatorjsCore: null, engine: "Theodore", available: true, altEngine: { type: "retroarch-web", embedPath: "vendor-retroarch-web/embed.html", core: "theodore" }, note: "Theodore (GPLv3), via RetroArch's web player. Covers TO7/TO7-70/TO8/TO8D/TO9/TO9+/MO5/MO6." },
  { id: "atarist", name: "Atari ST", group: "Atari", extensions: ["st"], emulatorjsCore: null, available: false, note: "Not currently supported by B-NAN's engine." },
  { id: "apple2", name: "Apple II", group: "Apple", extensions: ["dsk", "po"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "arduboy", name: "Arduboy", group: "Handheld", extensions: ["hex"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "chip8", name: "CHIP-8", group: "Virtual machine", extensions: ["ch8"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "fairchild_chanf", name: "Fairchild Channel F", group: "Fairchild", extensions: ["bin"], emulatorjsCore: null, available: false, note: "Checked directly: the only thing found was a single-author demo page with no source repository and no bundled ROMs -- not something that can responsibly be depended on or bundled." },
  { id: "odyssey2", name: "Magnavox Odyssey²", group: "Magnavox", extensions: ["bin"], emulatorjsCore: null, available: false, note: "Checked directly: the only \"play online\" options found were ad-supported ROM sites of unknown provenance, not open or embeddable software -- not something B-NAN will link to or depend on." },
  { id: "vectrex", name: "Vectrex", group: "GCE", extensions: ["vec"], emulatorjsCore: null, available: false, note: "Checked directly: the browser emulators that exist for this (jsvecx and forks) are effectively abandoned -- years with no commits, no documented way to embed them in another page." },
  { id: "pokemon_mini", name: "Pokémon Mini", group: "Nintendo", extensions: ["min"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "neogeocd", name: "Neo Geo CD", group: "SNK", extensions: ["cue", "bin"], emulatorjsCore: null, available: false, note: "Not wired up as its own system yet (regular arcade Neo Geo cartridges are covered under Arcade)." },
  { id: "neogeoaes", name: "Neo Geo AES", group: "SNK", extensions: ["zip"], emulatorjsCore: null, available: false, note: "Same underlying hardware/ROMs as arcade Neo Geo (MVS), which IS covered under Arcade (FinalBurn Neo) -- not wired up as a separate cartridge-console system." },
  { id: "xbox", name: "Xbox", group: "Microsoft", extensions: ["iso", "xiso"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "xemu" }, note: "No browser-ready core exists. Playable in the desktop builds ONLY, via a bundled native xemu — see docs/NATIVE_EMULATORS.md. Also needs your own Xbox BIOS/HDD image on first run, same bring-your-own-dumps policy as ROMs." },
  { id: "xbox360", name: "Xbox 360", group: "Microsoft", extensions: ["iso"], emulatorjsCore: null, available: false, note: "No browser-ready core exists, and no native desktop path either: Xenia is Windows-only (no macOS/Linux build at all) and is itself extremely hardware-demanding even natively, so it isn't in B-NAN's native-emulator lineup — a Windows-only system inside an app meant to run the same everywhere isn't a good fit. Still an honest 'no' today." },
  { id: "ps3", name: "PlayStation 3", group: "Sony", extensions: ["iso"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "rpcs3" }, note: "No browser-ready core exists. Playable in the Windows/Linux desktop builds via a bundled native RPCS3 — see docs/NATIVE_EMULATORS.md. RPCS3 has no official macOS build, so this stays unavailable on Mac regardless of what's bundled. Needs serious hardware even natively." },
  { id: "psvita", name: "PlayStation Vita", group: "Sony", extensions: ["vpk"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "vita3k" }, note: "No browser-ready core exists. Playable in the Windows/Linux desktop builds via a bundled native Vita3K — see docs/NATIVE_EMULATORS.md (macOS builds were discontinued upstream). Also needs your own PS Vita firmware on first run, same bring-your-own-dumps policy as ROMs." },
  { id: "wiiu", name: "Wii U", group: "Nintendo", extensions: ["wud", "wux"], emulatorjsCore: null, available: false, nativeEngine: { emulatorId: "cemu" }, note: "No browser-ready core exists. Playable in the Windows/Linux desktop builds via a bundled native Cemu — see docs/NATIVE_EMULATORS.md (Cemu has no official macOS build)." },
  { id: "philipscdi", name: "Philips CD-i", group: "Philips", extensions: ["chd", "cue"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "segaarcade3d", name: "Sega arcade (Model 2/3, Naomi, Triforce, Chihiro, Hikaru)", group: "Arcade", extensions: ["zip", "chd"], emulatorjsCore: null, available: false, note: "These are much more demanding than the arcade hardware B-NAN's Arcade/MAME systems already cover (CPS-1/2, Neo Geo MVS, and general MAME sets from the 70s-90s) -- no browser-ready core exists for this generation of 3D arcade hardware." },
  { id: "sharpx68000", name: "Sharp X68000", group: "Sharp", extensions: ["dim", "img"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "palmos", name: "Palm OS", group: "Palm", extensions: ["prc"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "doom", name: "Doom engine games", group: "PC", extensions: ["wad"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "quake", name: "Quake engine games", group: "PC", extensions: ["pak"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "scummvm", name: "Point-and-click (ScummVM)", group: "PC", extensions: ["scummvm"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "rpgmaker", name: "RPG Maker 2000/2003", group: "PC", extensions: ["ldb"], emulatorjsCore: null, available: false, note: "Not currently supported." },
  { id: "pdf", name: "PDF viewer", group: "Tools", extensions: ["pdf"], emulatorjsCore: null, available: false, note: "Not an emulator core, and not wired up — out of scope for now." },
  { id: "tic80", name: "TIC-80 (fantasy console)", group: "Fantasy console", extensions: ["tic"], emulatorjsCore: null, available: false, note: "Has its own official web player elsewhere; not embedded in B-NAN yet." },
  { id: "wasm4", name: "WASM-4 (fantasy console)", group: "Fantasy console", extensions: ["wasm"], emulatorjsCore: null, available: false, note: "Has its own official web player elsewhere; not embedded in B-NAN yet." },
  { id: "twenty48", name: "2048", group: "Puzzle", extensions: ["2048"], emulatorjsCore: null, available: false, note: "Not currently supported." },
];

// The full named-core wishlist, matched honestly against what actually
// runs. `available` mirrors the underlying system; `note` explains when
// the *named* core isn't literally what's running under the hood.
const RB_CORE_LIST = [
  { name: "2048", system: "2048", available: false },
  { name: "4DO", system: "Panasonic 3DO", available: true, note: "B-NAN plays 3DO via the Opera core, not 4DO." },
  { name: "Beetle PSX", system: "PlayStation", available: true, note: "B-NAN plays PSX via PCSX-ReARMed by default (Beetle PSX HW is available as an alternate)." },
  { name: "Beetle PSX HW", system: "PlayStation (hardware rendering)", available: true, note: "Available as the alternate PlayStation engine." },
  { name: "Beetle Saturn", system: "Sega Saturn", available: true, note: "B-NAN plays Saturn via Yabause, not Beetle Saturn." },
  { name: "Beetle SuperGrafx", system: "NEC SuperGrafx", available: true, note: "Runs via the PC Engine (Beetle PCE) core." },
  { name: "Beetle PCE", system: "PC Engine/TurboGrafx-16", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "Beetle PCE Fast", system: "Faster PC Engine", available: true, note: "B-NAN uses the standard Beetle PCE core, not the Fast variant." },
  { name: "Beetle PC-FX", system: "NEC PC-FX", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "Beetle VB", system: "Virtual Boy", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "Beetle WonderSwan", system: "WonderSwan", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "BlastEm", system: "Sega Genesis/Mega Drive", available: true, note: "B-NAN plays Genesis via Genesis Plus GX, not BlastEm." },
  { name: "blueMSX", system: "MSX, MSX2, ColecoVision", available: false, note: "ColecoVision is playable via a different core (GearColeco); MSX itself isn't wired up yet." },
  { name: "bsnes", system: "SNES", available: true, note: "Available as an alternate SNES engine, but only on the 'nightly' core channel in Settings — the stable channel plays SNES via Snes9x only." },
  { name: "bsnes HD Beta", system: "SNES (HD Mode 7)", available: true, note: "B-NAN's bsnes build doesn't include the HD Mode 7 beta features; regular bsnes/Snes9x are available." },
  { name: "Caprice32", system: "Amstrad CPC", available: false },
  { name: "Citra", system: "Nintendo 3DS", available: true, note: "B-NAN plays 3DS via Azahar, a Citra continuation — extremely demanding, expect rough performance." },
  { name: "CrocoDS", system: "Amstrad CPC", available: false },
  { name: "DeSmuME", system: "Nintendo DS", available: true, note: "Available as an alternate DS engine (default is melonDS)." },
  { name: "Dolphin", system: "GameCube, Wii", available: false, note: "No browser-ready build exists anywhere yet." },
  { name: "DOSBox Pure", system: "DOS PCs", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "DOSBox SVN", system: "DOS PCs", available: true, note: "B-NAN uses DOSBox Pure, not the SVN branch." },
  { name: "EasyRPG", system: "RPG Maker 2000/2003", available: false },
  { name: "ECWolf", system: "Wolfenstein 3D", available: false },
  { name: "Emux CHIP-8", system: "CHIP-8", available: false },
  { name: "FCEUmm", system: "NES/Famicom", available: true, note: "This is exactly the default engine B-NAN uses." },
  { name: "FinalBurn Neo", system: "Arcade, Neo Geo, CPS1/2/3", available: true, note: "This is exactly the default Arcade engine B-NAN uses." },
  { name: "Flycast", system: "Dreamcast, Naomi, Atomiswave", available: false },
  { name: "FreeChaF", system: "Fairchild Channel F", available: false },
  { name: "FreeIntv", system: "Intellivision", available: true, note: "This is exactly the engine B-NAN uses -- permanently vendored locally, not fetched from anywhere at runtime." },
  { name: "Frodo", system: "Commodore 64", available: true, note: "B-NAN plays C64 via VICE, not Frodo." },
  { name: "Fuse", system: "ZX Spectrum", available: false },
  { name: "Gambatte", system: "Game Boy, Game Boy Color", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "Gearboy", system: "Game Boy", available: true, note: "B-NAN plays Game Boy via Gambatte, not Gearboy." },
  { name: "Genesis Plus GX", system: "Master System, Genesis, Sega CD, Game Gear", available: true, note: "This is exactly the engine B-NAN uses across all four systems." },
  { name: "GPSP", system: "Game Boy Advance", available: true, note: "B-NAN plays GBA via mGBA, not GPSP." },
  { name: "Handy", system: "Atari Lynx", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "Hatari", system: "Atari ST", available: false },
  { name: "jsbeeb", system: "BBC Micro", available: true, note: "This is exactly the engine B-NAN uses -- not a libretro core, a standalone GPL-3.0 web emulator, vendored locally." },
  { name: "Sfotty Pie", system: "Atari 8-bit / XEGS", available: true, note: "This is exactly the engine B-NAN uses -- not a libretro core, a standalone MIT-licensed web emulator, vendored locally." },
  { name: "Atari800", system: "Atari 8-bit / XEGS", available: false, note: "Real and active, but native desktop C code with no official browser/WASM build -- B-NAN uses Sfotty Pie instead, which is browser-native." },
  { name: "JSSpeccy 3", system: "ZX Spectrum", available: true, note: "This is exactly the engine B-NAN uses -- not a libretro core, a standalone GPL-3.0 web emulator, vendored locally." },
  { name: "MAME", system: "Arcade", available: true, note: "B-NAN's MAME core is MAME 2003-Plus." },
  { name: "MAME 2000", system: "Arcade", available: true, note: "B-NAN uses MAME 2003/2003-Plus, not the 2000 build — most sets still work." },
  { name: "MAME 2003", system: "Arcade", available: true, note: "Available as the alternate MAME engine." },
  { name: "MAME 2003 Plus", system: "Arcade", available: true, note: "This is exactly the default MAME engine B-NAN uses." },
  { name: "MAME 2010", system: "Arcade", available: true, note: "B-NAN uses MAME 2003-Plus, not the 2010 build." },
  { name: "MAME 2015", system: "Arcade", available: true, note: "B-NAN uses MAME 2003-Plus, not the 2015 build." },
  { name: "MAME 2016", system: "Arcade", available: true, note: "B-NAN uses MAME 2003-Plus, not the 2016 build." },
  { name: "Mednafen", system: "Multiple classic systems", available: true, note: "Mednafen is the project behind the 'Beetle' cores that power PSX, Saturn, PCE, PC-FX, Virtual Boy, and WonderSwan here." },
  { name: "melonDS", system: "Nintendo DS", available: true, note: "This is exactly the default engine B-NAN uses." },
  { name: "mGBA", system: "Game Boy Advance", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "Mesen", system: "NES", available: true, note: "B-NAN plays NES via FCEUmm, not Mesen." },
  { name: "Mesen-S", system: "SNES", available: true, note: "B-NAN plays SNES via Snes9x/bsnes, not Mesen-S." },
  { name: "Mu", system: "Palm OS", available: false },
  { name: "MuPDF", system: "PDF viewer", available: false },
  { name: "NeoCD", system: "Neo Geo CD", available: false },
  { name: "Nestopia UE", system: "NES", available: true, note: "Available as the alternate NES engine." },
  { name: "NxEmu", system: "Nintendo Switch", available: false, note: "Real, active, and open-source — but native desktop software with very limited game compatibility today, not something with a browser/WASM build. Not wired into B-NAN; see the Switch row above for the full reasoning." },
  { name: "Opera", system: "3DO", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "ParaLLEl N64", system: "Nintendo 64", available: true, note: "Available as the alternate N64 engine (default is Mupen64Plus-Next)." },
  { name: "PicoDrive", system: "Genesis, Sega CD, 32X", available: true, note: "Available as an alternate engine for Genesis/Sega CD, and the default for 32X." },
  { name: "Play!", system: "PlayStation 2", available: false },
  { name: "PPSSPP", system: "PSP", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "PrBoom", system: "Doom engine", available: false },
  { name: "PUAE", system: "Commodore Amiga", available: true, note: "This is exactly the engine B-NAN uses -- also powers Amiga CD32 in CD32 mode." },
  { name: "PX68K", system: "Sharp X68000", available: false },
  { name: "Cemu", system: "Wii U", available: false, note: "Native desktop software, no browser build exists." },
  { name: "Xemu", system: "Xbox", available: false, note: "Native desktop software, no browser build exists." },
  { name: "Xenia", system: "Xbox 360", available: false, note: "Native desktop software, no browser build exists, and it's extremely demanding even natively." },
  { name: "RPCS3", system: "PlayStation 3", available: false, note: "Native desktop software, no browser build exists, and it's extremely demanding even natively." },
  { name: "Vita3K", system: "PlayStation Vita", available: false, note: "Native desktop software, no browser build exists." },
  { name: "Model 2 emulator", system: "Sega Model 2 arcade", available: false, note: "No browser-ready core exists for this hardware generation." },
  { name: "Model 3 emulator (Supermodel)", system: "Sega Model 3 arcade", available: false, note: "No browser-ready core exists for this hardware generation." },
  { name: "Flycast (Naomi/Atomiswave)", system: "Sega Naomi", available: false, note: "Same Flycast project as Dreamcast -- no browser build wired into B-NAN's engine." },
  { name: "QuickNES", system: "NES", available: true, note: "B-NAN plays NES via FCEUmm/Nestopia, not QuickNES." },
  { name: "Race", system: "Neo Geo Pocket", available: true, note: "B-NAN plays Neo Geo Pocket via Beetle NGP, not Race." },
  { name: "Redream", system: "Dreamcast", available: false },
  { name: "Ryujinx", system: "Nintendo Switch", available: false, note: "Shut down in 2024 following Nintendo's legal action against its maintainer. No longer distributed by its authors; B-NAN doesn't bundle or link to it." },
  { name: "SameBoy", system: "Game Boy, Game Boy Color", available: true, note: "B-NAN plays Game Boy via Gambatte, not SameBoy." },
  { name: "ScummVM", system: "Point-and-click adventure games", available: false },
  { name: "Snes9x", system: "SNES", available: true, note: "This is exactly the default engine B-NAN uses." },
  { name: "Stella", system: "Atari 2600", available: true, note: "B-NAN uses Stella 2014, the newer build." },
  { name: "Stella 2014", system: "Atari 2600", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "SwanStation", system: "PlayStation", available: true, note: "B-NAN plays PSX via PCSX-ReARMed/Beetle PSX HW, not SwanStation." },
  { name: "TIC-80", system: "Fantasy console", available: false },
  { name: "TyrQuake", system: "Quake", available: false },
  { name: "UAE4ARM", system: "Amiga", available: true, note: "B-NAN plays Amiga via PUAE, not UAE4ARM." },
  { name: "VICE x64", system: "Commodore 64", available: true, note: "This is exactly the engine B-NAN uses (the x64sc variant)." },
  { name: "VICE x128", system: "Commodore 128", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "VICE xPET", system: "Commodore PET", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "VICE xPlus4", system: "Commodore Plus/4", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "VICE xSC", system: "VIC-20", available: true, note: "B-NAN plays VIC-20 via VICE's xvic build; 'xSC' usually refers to the C64 variant, covered separately." },
  { name: "VitaQuake", system: "Quake", available: false },
  { name: "Virtual Jaguar", system: "Atari Jaguar", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "WASM-4", system: "Fantasy console", available: false },
  { name: "YabaSanshiro", system: "Sega Saturn", available: true, note: "B-NAN plays Saturn via Yabause, not YabaSanshiro." },
  { name: "Yabause", system: "Sega Saturn", available: true, note: "This is exactly the engine B-NAN uses." },
  { name: "yuzu", system: "Nintendo Switch", available: false, note: "Shut down in 2024 following Nintendo's legal action against its maintainers. No longer distributed by its authors; B-NAN doesn't bundle or link to it." },
];
